import { z } from "zod";

// Core stages are fixed for scoring logic
export const CoreStageSchema = z.enum(["explore", "consider", "compare", "decide"]);
export type CoreStage = z.infer<typeof CoreStageSchema>;

// Personas and stages are now strings from config
// These schemas validate non-empty strings
export const PersonaSchema = z.string().min(1, "Persona cannot be empty");
export const StageSchema = z.string().min(1, "Stage cannot be empty");

export type Persona = string;
export type Stage = string;

export const IntentSchema = z.object({
  id: z.string(),
  persona: PersonaSchema,
  stage: StageSchema,
  text: z.string().min(1).max(200),
  defaultQueries: z.array(z.string()).optional(),  // Legacy, now generated by DeepSeek
  role: z.enum(["cpo", "family_unit"]).default("cpo"),
  queryStyle: z.number().min(0.5).max(1.0).default(0.75),  // 0.5=common, 1.0=niche
  generatedQueries: z.array(z.string()).optional(), // Queries generated by AI
  generatedQueriesAt: z.string().datetime().optional(), // Timestamp for latest generated queries
  createdAt: z.string().datetime(),
  active: z.boolean().default(true),
});

export type Intent = z.infer<typeof IntentSchema>;

// UI runtime type
export interface IntentNode {
  id: string;
  text: string;
  role: "cpo" | "family_unit";
  queryStyle: number;  // 0.5 (common) to 1.0 (niche)
  generatedQueries?: string[];  // Queries generated by DeepSeek (UI state only)
}

export const IntentChangeSchema = z.object({
  action: z.enum(["created", "modified", "deactivated", "reactivated"]),
  intentId: z.string(),
  field: z.string().optional(),
  oldValue: z.unknown().optional(),
  newValue: z.unknown().optional(),
});

export type IntentChange = z.infer<typeof IntentChangeSchema>;

export const IntentHistoryEntrySchema = z.object({
  version: z.number().int().positive(),
  date: z.string(),
  changes: z.array(IntentChangeSchema),
});

export type IntentHistoryEntry = z.infer<typeof IntentHistoryEntrySchema>;

export const IntentLibrarySchema = z.object({
  version: z.number().int().nonnegative(),
  updatedAt: z.string().datetime(),
  intents: z.array(IntentSchema),
  history: z.array(IntentHistoryEntrySchema),
});

export type IntentLibrary = z.infer<typeof IntentLibrarySchema>;

export function generateIntentId(persona: Persona, stage: Stage): string {
  const timestamp = Date.now().toString(36);
  return `int_${persona}_${stage}_${timestamp}`;
}

export function getCellKey(persona: Persona, stage: Stage): string {
  return `${persona}_${stage}`;
}

export function parseCellKey(key: string): { persona: Persona; stage: Stage } | null {
  // Key format: "persona_stage" where persona may contain underscores
  // Find the last underscore to split persona from stage
  const lastUnderscore = key.lastIndexOf("_");
  if (lastUnderscore === -1) {
    return null;
  }
  const persona = key.slice(0, lastUnderscore);
  const stage = key.slice(lastUnderscore + 1);
  if (persona && stage) {
    return { persona, stage };
  }
  return null;
}
